service: serverless-pdf-generator

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  apiGateway:
    binaryMediaTypes:
      - '*/*'

functions:
  generatePdf:
    handler: dist/handlers/pdfHandler.generatePdf
    events:
      - http:
          path: generate-pdf
          method: post

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000
  IS_OFFLINE: ${env:IS_OFFLINE, "false"}
